services:
  lab12:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env # loads OPENAI_API_KEY at runtime
    environment:
      - PYTHONUNBUFFERED=1 # unbuffered stdout/stderr
    restart: unless-stopped
