services:
  livenote:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - ./models:/app/models
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
