"""add user_id FK to email_verifications

Revision ID: c3c830a8e197
Revises: 5cfae8cf99e5
Create Date: 2025-05-02 21:49:59.203291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c830a8e197'
down_revision: Union[str, None] = '5cfae8cf99e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'email_verifications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_verifications', type_='foreignkey')
    op.drop_column('email_verifications', 'user_id')
    # ### end Alembic commands ###
